### ISSUE TITLE
(RISC OS, HPBridge) With two fileserver directories mounted, both have the same content in the RO filer

### ISSUE THREAD

**Issue by philpem** [cr12925/PiEconetBridge#15]
Steps to reproduce:

* Create two directories under `~/econetfs`, e.g. `0Users` and `1Applications`. Create some files in each directory
* Middle-click `Net` icon on RISC OS client (v4.02 used for this test). Select "FS List".
* Log onto one of the FSes, e.g. `Users`, as `syst`.
* Click the second FS icon, e.g. `Applications`.
* Note that both directory windows show the same directory content, that of the first fileserver.

Next to show this is being tracked somewhat correctly when only one is mounted:
* Middle-click the FS icons on the iconbar and "Bye" from both.
* Log onto one of the FSes (either)
* Middle-click the FS icon and select "Bye"
* Log onto the other FS -- now the other FS's files will be visible.

This isn't behaving as expected -- normally with a Level 4 Fileserver, multiple drives can be shared, and the server will correctly reference each of them. For instance, a CD-ROM and a hard drive can be shared, each with a different set of tiles available.

**Comment by cr12925** [comment]
We think this is a RISC OS bug.
