### ISSUE TITLE
PI Username hard coded

### ISSUE THREAD

**Issue by ukwebb** [cr12925/PiEconetBridge#17]
Issue : 
The "pi" username  is hardcoded which causes issues with the updated pi imager and other potential security issues ( ie using the default username) 

eg : some places where "pi" is hard coded; e.g. the systemd startup file has "User=pi" and "Group=pi". This will need to be changed to the picked user. And, of course, the default config files reference /home/pi/econetfs

This is due to a change in the PI imager tool which no longer creates a default user called 'pi' and instead uses the currently logged in username .

more info here : https://stardot.org.uk/forums/viewtopic.php?p=394820#p394820

Requested Solution :
On stardot Chris mentioned : "Just needs use of the whoami command, and some sed scripts to fix the systemd templates…"

Temporary Work Around : 
Until such time as Chris can get the necessary updates made - the username PI must be create in the imager tool

**Comment by cr12925** [comment]
Now removed.
