### ISSUE TITLE
If a user changes their password to one wrapped in quotes, they can no longer log in

### ISSUE THREAD

**Issue by marrold** [cr12925/PiEconetBridge#18]
I made the mistake of changing a users password to one wrapped in quotes, e.g

`*PASS "" "SAUSAGE"`

and now they are unable to login. Having checked the Password file I can see that it's included the quotes, but if I include them when attempting to login I get a wrong password error. I get the same error if I don't include them.

**Comment by cr12925** [comment]
Will aim to fix in 2.1
